### ISSUE TITLE
Write a Go program to print "Hello World"

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/hello-world#28]
### Description

Write a Go program to print "Hello World"

> **Note** Save `hello-world.go` inside the `hello-world` folder

**Comment by ArielaRfa** [comment]
Okey i take this issues

**Comment by harshraj8843** [comment]
Hey @ArielaRfa 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned 🤗 

```
!assign
```

**Comment by sancoLgates** [comment]
!assign
