### ISSUE TITLE
Write a Befunge program to print "Hello World"

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/hello-world#610]
### Description

Write a Befunge program to print "Hello World"

> **Note** Save the file as `hello-world.befunge` inside the [`hello-world/befunge/`](https://github.com/codinasion/hello-world/tree/master/hello-world/befunge) folder

**Comment by JacobKerames** [comment]
I'd like to be assigned this issue if it is not taken. Thank you.

**Comment by JacobKerames** [comment]
!assign
