### ISSUE TITLE
Write a Golo program to print "Hello World"

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/hello-world#714]
### Description

Write a Golo program to print "Hello World"

> **Note** Save `hello-world.golo` inside the `hello-world` folder

**Comment by Rayan1605** [comment]
Hi @harshraj8843! 

Does this issue still need worked on? 
If it does I will be happy to get it done

**Comment by harshraj8843** [comment]
Hey @Rayan1605 

All the open issues are available for contribution 🤗 

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned

```
!assign
```

**Comment by Rayan1605** [comment]
Thank you very much. I am just new to the site, so I wanted to make sure I understood

**Comment by Rayan1605** [comment]
!assign
