### ISSUE TITLE
Write a Objective-C program to print "Hello World"

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/hello-world#732]
### Description

Write a Objective-C program to print "Hello World"

> **Note** Save `hello-world.h` inside the `hello-world` folder

**Comment by flamesjames** [comment]
Hey there @harshraj8843! Does this issue still need worked on? If so, I would be glad to help out with it.

**Comment by harshraj8843** [comment]
Yes @flamesjames 

All open issues are available for contribution

You can comment `!assign` on any `good first issue` you want to contribute to, to be auto-assigned 🤗 

```
!assign
```

**Comment by flamesjames** [comment]
Thank you for the info! I am very new to GH so I appreciate you helping out - I never knew that you could do that. I will get this done today.

**Comment by flamesjames** [comment]
!assign

**Comment by harshraj8843** [comment]
> I never knew that you could do that.

It's not the default feature provided by Github but we manage to do that using a script https://github.com/codinasion/hello-world/blob/master/script/auto_assign_issue.py 🤗

**Comment by flamesjames** [comment]
@harshraj8843 - should this be closed as well? Fixed with #731

**Comment by harshraj8843** [comment]
Hey @flamesjames 

Issue #731 is for `hello-world.m` and this issue is for `hello-world.m`

**Comment by flamesjames** [comment]
@harshraj8843 - ahh got you now, `.m` and `.h` files both. In that case, I will have to slightly modify my `.m` file merged with #731
