### ISSUE TITLE
Write a Solidity program to print "Hello World" 

### ISSUE THREAD

**Issue by Petrosdevri** [codinasion/hello-world#743]
### Description

Write a Solidity program to print "Hello World"

> **Note** Save `hello-world.sol` inside the `hello-world` folder

**Comment by harshraj8843** [comment]
Hey @Petrosdevri 

Thanks for showing your interest 😃 

You can raise a PR with the `hello-world.sol` file inside the `hello-world` folder 
and link this issue with the PR using `Closes #743` 🤗
