### ISSUE TITLE
New Folder Structure for the Hello Word Directory

### ISSUE THREAD

**Issue by canaleal** [codinasion/hello-world#745]
### Description

I think it would be a good idea to restructure the hello-word folder to include sub directories for each language/framework. 
For example, the R programming language files are out of order alphabetically using the current system, making it difficult to navigate the repository. 

### Screenshots

![image](https://user-images.githubusercontent.com/49886351/214498033-ac642bf7-9383-4c80-84e6-75d1bc2dff77.png)

All of these files will be out of order in the current file structure. 

![image](https://user-images.githubusercontent.com/49886351/214498163-3ddbc760-54c1-4004-8812-930255d98875.png)

### Code of Conduct

- [X] I have read and agree to the Codinasion project's [Code of Conduct](CODE_OF_CONDUCT.md)

**Comment by harshraj8843** [comment]
File structure updated 😍 

Thanks 🤗
